#! /usr/bin/env python3
# coding: utf-8
###############################################################################
# FILE     : settings.py
# SYNOPSIS : Settings file for FindCStyleCasts.py.
# LICENSE  : MIT
###############################################################################


###############################################################################
# CONSTANTS
###############################################################################

# Every type to look for as a type cast
TYPES = (
    'void',
    'char',
    'short',
    'int',
    'long',
    'float',
    'double',
    'HANDLE',
    'HBITMAP',
    'HBRUSH',
    'HCOLORSPACE',
    'HCONV',
    'HCONVLIST',
    'HCURSOR',
    'HDC',
    'HDDEDATA',
    'HDESK',
    'HDROP',
    'HDWP',
    'HENHMETAFILE',
    'HFILE',
    'HFONT',
    'HGDIOBJ',
    'HGLOBAL',
    'HHOOK',
    'HICON',
    'HINSTANCE',
    'HKEY',
    'HKL',
    'HLOCAL',
    'HMENU',
    'HMETAFILE',
    'HMODULE',
    'HMONITOR',
    'HPALETTE',
    'HPEN',
    'HRESULT',
    'HRGN',
    'HRSRC',
    'HSZ',
    'HWINSTA',
    'HWND',
    'INT',
    'INT8',
    'INT16',
    'INT32',
    'INT64',
    'LANGID',
    'LCID',
    'LCTYPE',
    'LGRPID',
    'LONG',
    'LONGLONG',
    'LONG32',
    'LONG64',
    'LPARAM',
    'LPBOOL',
    'LPBYTE',
    'LPCOLORREF',
    'LPCSTR',
    'LPCTSTR',
    'LPCVOID',
    'LPCWSTR',
    'LPDWORD',
    'LPHANDLE',
    'LPINT',
    'LPLONG',
    'LPSTR',
    'LPTSTR',
    'LPVOID',
    'LPWORD',
    'LPWSTR',
    'LRESULT',
    'PBOOL',
    'PBOOLEAN',
    'PBYTE',
    'PCHAR',
    'PCSTR',
    'PCTSTR',
    'PCWSTR',
    'PDWORD',
    'PDWORDLONG',
    'PDWORD32',
    'PDWORD64',
    'PFLOAT',
    'PHANDLE',
    'PHKEY',
    'PINT',
    'PINT8',
    'PINT16',
    'PINT32',
    'PINT64',
    'PLCID',
    'PLONG',
    'PLONGLONG',
    'PLONG32',
    'PLONG64',
    'PSHORT',
    'PSTR',
    'PTBYTE',
    'PTCHAR',
    'PTSTR',
    'PUCHAR',
    'PUINT',
    'PUINT8',
    'PUINT16',
    'PUINT32',
    'PUINT64',
    'PULONG',
    'PULONGLONG',
    'PULONG32',
    'PULONG64',
    'PUSHORT',
    'PVOID',
    'PWCHAR',
    'PWORD',
    'PWSTR',
    'QWORD',
    'SHORT',
    'TBYTE',
    'TCHAR',
    'UCHAR',
    'UINT',
    'UINT8',
    'UINT16',
    'UINT32',
    'UINT64',
    'ULONG',
    'ULONGLONG',
    'ULONG32',
    'ULONG64',
    'USHORT',
    'USN',
    'VOID',
    'WCHAR',
    'WINAPI',
    'WORD',
    'WPARAM'
)

# The number of type alternatives to search for per regular expression
REGEX_TYPES_SLICE_STRIDE = 10

# Set the logging level to one of:
#     {'debug', 'info', 'warning', 'error', 'critical'}
LOGGING = 'warning'


###############################################################################
# END
###############################################################################
# Local variables:
# mode: python
# End:
